name: sentc
description: An end to end encryption sdk for every developer. The sdk is focused on group encryption and supports child and connected groups.
version: 0.15.0
homepage: https://sentc.com/
documentation: https://sentc.com/
repository: https://github.com/sentclose/sentc-flutter
topics:
  - crypto
  - sdk
  - sentc
  - encryption

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.82.1
  ffi: ^2.0.1
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  sentc_common: ^0.10.0
   #path: ../sentc_common   #local dev
  path: ^1.8.1
  meta: ^1.9.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  ffigen: ^8.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.sentclose.sentc
        pluginClass: SentcPlugin
     # ios:
      #  pluginClass: SentcPlugin
      linux:
        pluginClass: SentcPlugin
     # macos:
      #  pluginClass: SentcPlugin
      windows:
        pluginClass: SentcPluginCApi
     # web:
      #  pluginClass: SentcWeb
      #  fileName: sentc_web.dart