name: sentc_common
description: Common functions for the sentc and sentc light sdks. Sentc is an end-to-end encryption sdk with user and group management.
version: 0.10.0
homepage: https://sentc.com/
documentation: https://sentc.com/
repository: https://github.com/sentclose/sentc-flutter
topics:
  - crypto
  - sdk
  - sentc
  - encryption

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

