name: sentc_light
description: Sentc sdk light with user and group management.
version: 0.10.0
homepage: https://sentc.com/
documentation: https://sentc.com/
repository: https://github.com/sentclose/sentc-flutter
topics:
  - crypto
  - sdk
  - sentc
  - encryption

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.77.0
  ffi: ^2.0.1
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  sentc_common: 0.10.0
    #path: ../sentc_common   #local dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^8.0.2
  build_runner: ^2.1.11

flutter:
  plugin:
    platforms:
      android:
        package: com.sentclose.sentc_light.sentc_light
        pluginClass: SentcLightPlugin
#      ios:
#        pluginClass: SentcLightPlugin
      linux:
        pluginClass: SentcLightPlugin
#      macos:
#        pluginClass: SentcLightPlugin
      windows:
        pluginClass: SentcLightPluginCApi
#      web:
#        pluginClass: SentcLightWeb
#        fileName: sentc_light_web.dart
