name: sentc_light
description: "Sentc sdk light with user and group management."
version: 0.13.1
homepage: https://sentc.com/
documentation: https://sentc.com/
repository: https://github.com/sentclose/sentc-flutter
topics:
  - crypto
  - sdk
  - sentc
  - encryption

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.9.0
  plugin_platform_interface: ^2.0.2
  sentc_common: ^0.10.0
  #path: ../sentc_common   #local dev

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
